services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/events_db

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

volumes:
  db_data:
